import Header from "./components/Header"

export const metadata = {
  title: {
    
    default:"this is default title",
    template : "%s | this is static title"
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <body>
        <Header/>
        {children}
        <footer>footer</footer>
        </body>
    </html>
  )
}
